(function () {
  const processNames = [
    "Proactive Daily Limit Increase - Master Agents (EU)",
    "RPA Master Report",
    "AFN Trace Of Funds",
    "RMO Refund Request Pull From Oracle",
    "Daily AUSTRAC Extract",
    "Care PPS Webcare Digital Fraud Errors Cases Handling",
    "Network APN Send Delayed TXN Notification",
    "DRT High band KYC case creation",
    "CFO JE Upload",
    "CEM Health Check Of Journeys and Campaigns",
    "APN MT Status Inquiry",
    "AR Review and Collection Process (Germany and Austria)",
    "Pre-Suspension of Agents (US Vigo Independent)",
    "Care Manual Refunds",
    "Compliance Digital Decline",
    "CFO OBIEE Report extraction",
    "Credit Finance Agent Reconciliations AU NZ",
    "Care QQC Refunds",
    "Partner Management Approve Vendor Access Requests",
    "Digital Collections - EmpArchive Email Download",
    "AR Review and Collection (AU, NZ, JP)",
    "Settlement LAROC - OWC reports downloading",
    "Argentina Settlement Bank Registration",
    "Argentina Settlement Bank Registration - Recibo",
    "Credit and Risk Reconciliation Spain Automation",
    "Proactive Dynamic Daily Limit Increase (Japan)",
    "AR Review and Collection Process France",
    "AR Review and Collection Process France - Stage 2",
    "DRT Comment in CTM",
    "Argentina - Request for Additional Documentation",
    "AR Collections cases follow up (France)",
    "AR Review and Agents Reactivation (UK)",
    "FIU International Subpoena Referrals 1st",
    "FIU International Subpoena Referrals 2nd",
    "FIU International Subpoena Referrals - Reporting",
    "WFM Genesys Annex Data Extract",
    "AROC Refund D2B TXN Rejected By Bank",
    "Partner Services - Refund TXN from D2B Rejects Queue in CTM",
    "Credit and Risk Pro-Active Dynamic Limits for Agents BR (Argentina)",
    "Brazil Operations - GCO OBP DTB Payments",
    "GSI Second Attempt Email Notification",
    "Digital unbilled reclasses preparation in ORMB",
    "Settlement Ops - Write Offs Entering in ORMB",
    "IAM IBIS Upload",
    "Care MT Name Change",
    "Proactive Dynamic Daily Limits for Agents (Africa)",
    "GSI Sanctions outreach",
    "GSI Bank Inquiry notification",
    "DRT CTM comment for Unsettled transactions",
    "CFO Invoice Downloading",
    "GFC Case Investigation",
    "GFC CPI GSI Hit Follow Up",
    "GFC Fraud Warning and CPI GSI Hit Review",
    "GFC FTC9 Exceptions Review",
    "RMO MTCN Generation in CTM (Cash Pick-up)",
    "Argentina Acct Digital Billing Reconciliation MT",
    "Settlement Ops - iCare Cases Distribution",
    "Global NPC Document Request",
    "Care PPS Deactivate Account",
    "AR Collections (APAC Master Network Agents)",
    "Agent Enrollment South America Agents",
    "KYC ECDD Manual Case Creation",
    "WFM GCX CSR iPass Requests Approval",
    "Argentina - SMS for APN Receivers Enrollment",
    "Digital unbilled reclasses approval in ORMB",
    "Digital Collections - POP Request",
    "NPC FLA Investigation",
    "RMO Settlement - Keying Batches",
    "ALM Agent Setup Credit Trac",
    "Supply Chain - APA",
    "GSI - Hourly Report",
    "KYC PEP LVL 2",
    "Sanctions Screening Refresh",
    "Customer Onboarding Validation",
    "Loan Servicing Exception Handler"
  ];

  window.RPA = window.RPA || {};
  window.RPA.processNames = {
    list: processNames
  };
})();
